from DataAccess.DABase import DABase
from Models.RequestApiModels.ApplicationRequestAPI import ApplicationRequestAPI, ApplicationSaveRequestAPI
from Models.Response import Response
from Static.ActionTypes import ApplicationAction


class DAApplication(DABase):
    """Same actions for sp_birth / sp_death / sp_marriage / sp_nic - the subclass only sets ProcedureName."""

    AllowedDataFields = None
    AllowStatusUpdate = True

    def _ValidateData(self, requestAPI: ApplicationSaveRequestAPI) -> Response | None:
        if self.AllowedDataFields is None:
            return None
        if not isinstance(requestAPI.data, dict):
            return self._Fail(400, "Application data must be an object.")
        unknown_fields = set(requestAPI.data) - self.AllowedDataFields
        if unknown_fields:
            fields = ", ".join(sorted(unknown_fields))
            return self._Fail(400, f"Unsupported application field(s): {fields}.")
        return None

    def Dashboard(self, requestAPI: ApplicationRequestAPI) -> Response:
        # 2 result sets: [new_entries, pending, approved] and [last 5 applications]
        return self._Execute(requestAPI, ApplicationAction.DASHBOARD, "Dashboard", sets=[("summary", "row"), ("recent", "rows")])

    def List(self, requestAPI: ApplicationRequestAPI) -> Response:
        return self._Execute(requestAPI, ApplicationAction.LIST, "List", "rows")

    def Get(self, requestAPI: ApplicationRequestAPI) -> Response:
        return self._Execute(requestAPI, ApplicationAction.GET, "Get", "row")

    def Create(self, requestAPI: ApplicationSaveRequestAPI) -> Response:
        if self.AllowedDataFields is not None and requestAPI.app_id is not None:
            return self._Fail(400, "The application ID is generated by the database.")
        failure = self._ValidateData(requestAPI)
        if failure is not None:
            return failure
        if requestAPI.status not in {"Draft", "Pending"}:
            return self._Fail(400, "New applications must be saved as Draft or Pending.")
        requestAPI.signoff_officer_id = None
        if requestAPI.status == "Pending":                       # saving straight as Pending needs the sign-off officer
            failure = self._VerifySignoff(requestAPI, "Create")
            if failure is not None:
                return failure
        return self._Execute(requestAPI, ApplicationAction.CREATE, "Create", "row")

    def Update(self, requestAPI: ApplicationSaveRequestAPI) -> Response:
        if not requestAPI.app_id or requestAPI.app_id <= 0:
            return self._Fail(400, "A positive application ID is required.")
        if not self.AllowStatusUpdate and requestAPI.status is not None:
            return self._Fail(400, "Application status can only be changed through the workflow actions.")
        failure = self._ValidateData(requestAPI)
        if failure is not None:
            return failure
        requestAPI.signoff_officer_id = None
        return self._Execute(requestAPI, ApplicationAction.UPDATE, "Update", "row")

    def Submit(self, requestAPI: ApplicationSaveRequestAPI) -> Response:       # Draft -> Pending
        if not requestAPI.app_id or requestAPI.app_id <= 0:
            return self._Fail(400, "A positive application ID is required.")
        failure = self._VerifySignoff(requestAPI, "Submit")
        if failure is not None:
            return failure
        return self._Execute(requestAPI, ApplicationAction.SUBMIT, "Submit", "row")

    def Delete(self, requestAPI: ApplicationSaveRequestAPI) -> Response:       # only own Draft
        requestAPI.signoff_officer_id = None
        return self._Execute(requestAPI, ApplicationAction.DELETE, "Delete", "row")
