import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { File, Paths } from 'expo-file-system';

export interface CertificatePdfLine {
  label: string;
  value: string;
}

const esc = (value: unknown) =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const buildHtml = (title: string, ref: string, status: string, lines: CertificatePdfLine[]) => {
  const rows = lines
    .map((line) => `<tr><td class="k">${esc(line.label)}</td><td>${esc(line.value)}</td></tr>`)
    .join('');
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8" />
<style>
  @page { margin: 28px; }
  body { font-family: Arial, Helvetica, sans-serif; color: #1a1a1a; font-size: 13px; }
  .head { background: #0A1F44; color: #fff; padding: 18px; border-radius: 6px; text-align: center; }
  .head p { margin: 0; font-size: 11px; letter-spacing: 0.4px; color: #C9D1E3; }
  .head h1 { margin: 8px 0 0 0; font-size: 22px; }
  .ref { text-align: center; margin: 14px 0 4px 0; color: #666; }
  .status { text-align: center; font-weight: 700; letter-spacing: 1px; color: #0A1F44; margin-bottom: 12px; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 9px 4px; border-bottom: 1px solid #e6dcc4; vertical-align: top; }
  td.k { width: 150px; color: #7A6844; font-size: 11px; font-weight: 700; }
  .foot { margin-top: 28px; font-size: 10px; color: #777; text-align: center; }
</style></head>
<body>
  <div class="head">
    <p>Democratic Socialist Republic of Sri Lanka</p>
    <h1>${esc(title)}</h1>
  </div>
  <p class="ref">Ref ${esc(ref)}</p>
  <p class="status">${esc(status)}</p>
  <table>${rows}</table>
  <div class="foot">Generated by CiviLanka. This is a register preview, not a separately issued certificate.</div>
</body></html>`;
};

/** Builds the certificate PDF and opens the phone share sheet so it can be saved. */
export async function downloadCertificatePdf(title: string, ref: string, status: string, lines: CertificatePdfLine[]) {
  const { base64 } = await Print.printToFileAsync({
    html: buildHtml(title, ref, status, lines),
    width: 595,
    height: 842,
    base64: true,
  });
  if (!base64) throw new Error('The PDF could not be created.');

  const safeRef = ref.replace(/[^A-Za-z0-9]+/g, '_');
  const target = new File(Paths.cache, `CiviLanka_${safeRef}.pdf`);
  target.create({ overwrite: true });
  target.write(Uint8Array.from(atob(base64), (ch) => ch.charCodeAt(0)));

  if (!(await Sharing.isAvailableAsync())) {
    throw new Error('Saving or sharing files is not available on this device.');
  }
  await Sharing.shareAsync(target.uri, {
    mimeType: 'application/pdf',
    UTI: 'com.adobe.pdf',
    dialogTitle: `${title} ${ref}`,
  });
}
