import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { File, Paths } from 'expo-file-system';

export interface PdfReport {
  report_id?: number;
  report_type: string;
  from_date: string;
  to_date: string;
  total_applications: number;
  approved_count: number;
  pending_count: number;
  rejected_count: number;
  created_at?: string;
}

export interface PdfCategory {
  category: string;
  total: number;
  approved: number;
  pending: number;
  rejected: number;
}

const esc = (v: unknown) =>
  String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const day = (s?: string) => (s ? String(s).slice(0, 10) : '-');

const buildHtml = (r: PdfReport, cats: PdfCategory[] | null, generatedBy: string) => {
  const rate = r.total_applications > 0 ? Math.round((r.approved_count / r.total_applications) * 100) : 0;
  const catRows = (cats ?? [])
    .map(
      (c) =>
        `<tr><td>${esc(c.category)}</td><td class="n">${c.total}</td><td class="n">${c.approved}</td><td class="n">${c.pending}</td><td class="n">${c.rejected}</td></tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8" />
<style>
  @page { margin: 28px; }
  body { font-family: Arial, Helvetica, sans-serif; color: #1a1a1a; font-size: 12px; }
  .head { background: #0A1F44; color: #fff; padding: 16px 18px; border-radius: 6px; }
  .head h1 { margin: 0; font-size: 18px; }
  .head p { margin: 4px 0 0 0; font-size: 11px; color: #C9D1E3; }
  h2 { font-size: 13px; color: #0A1F44; margin: 22px 0 8px 0; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #0A1F44; color: #fff; text-align: left; padding: 7px 8px; font-size: 11px; }
  td { padding: 7px 8px; border-bottom: 1px solid #e5e5e5; }
  .n { text-align: right; }
  .meta td { border: none; padding: 3px 0; }
  .meta td.k { color: #666; width: 130px; }
  .tiles { width: 100%; border-collapse: separate; border-spacing: 8px 0; margin: 0 -8px; }
  .tile { border: 1px solid #ddd; border-radius: 6px; padding: 10px; text-align: center; }
  .tile b { display: block; font-size: 22px; color: #0A1F44; margin-top: 4px; }
  .tile span { font-size: 9px; letter-spacing: 1px; color: #666; }
  .foot { margin-top: 30px; font-size: 10px; color: #777; text-align: center; }
</style></head>
<body>
  <div class="head">
    <h1>CiviLanka - Applications Report</h1>
    <p>Department of Registrar General</p>
  </div>

  <h2>Report details</h2>
  <table class="meta">
    <tr><td class="k">Certificate type</td><td>${esc(r.report_type)}</td></tr>
    <tr><td class="k">Period</td><td>${esc(day(r.from_date))} to ${esc(day(r.to_date))}</td></tr>
    <tr><td class="k">Generated by</td><td>${esc(generatedBy || '-')}</td></tr>
    <tr><td class="k">Generated on</td><td>${esc(day(r.created_at) !== '-' ? day(r.created_at) : new Date().toISOString().slice(0, 10))}</td></tr>
  </table>

  <h2>Summary</h2>
  <table class="tiles"><tr>
    <td class="tile"><span>TOTAL</span><b>${r.total_applications}</b></td>
    <td class="tile"><span>APPROVED</span><b>${r.approved_count}</b></td>
    <td class="tile"><span>PENDING</span><b>${r.pending_count}</b></td>
    <td class="tile"><span>REJECTED</span><b>${r.rejected_count}</b></td>
  </tr></table>
  <p>Approval rate: <b>${rate}%</b></p>

  ${
    cats
      ? `<h2>By certificate type</h2>
  <table>
    <tr><th>Type</th><th class="n">Total</th><th class="n">Approved</th><th class="n">Pending</th><th class="n">Rejected</th></tr>
    ${catRows || '<tr><td colspan="5">No applications in this period.</td></tr>'}
  </table>`
      : ''
  }

  <div class="foot">Generated by CiviLanka - this document is system generated.</div>
</body></html>`;
};

/** Builds the PDF and opens the phone's share sheet (Save to Drive / Files / WhatsApp / Print ...). */
/** Builds the PDF and opens the phone's share sheet (Save to Drive / Files / WhatsApp / Print ...). */
/** Builds the PDF and opens the phone's share sheet (Save to Drive / Files / WhatsApp / Print ...). */
export async function downloadReportPdf(report: PdfReport, byCategory: PdfCategory[] | null, generatedBy: string) {
  // Ask for the PDF as base64 so we never have to read the file expo-print wrote.
  const { base64 } = await Print.printToFileAsync({
    html: buildHtml(report, byCategory, generatedBy),
    width: 595,
    height: 842,
    base64: true,
  });
  if (!base64) throw new Error('The PDF could not be created.');

  // Write our own copy into the app cache folder (readable by the share sheet).
  const safeType = String(report.report_type).replace(/[^A-Za-z0-9]+/g, '_');
  const name = `CiviLanka_${safeType}_${day(report.from_date)}_to_${day(report.to_date)}.pdf`;
  const target = new File(Paths.cache, name);
  target.create({ overwrite: true });
  target.write(Uint8Array.from(atob(base64), (ch) => ch.charCodeAt(0)));

  if (!(await Sharing.isAvailableAsync())) {
    throw new Error('Saving or sharing files is not available on this device.');
  }
  await Sharing.shareAsync(target.uri, {
    mimeType: 'application/pdf',
    UTI: 'com.adobe.pdf',
    dialogTitle: `Report ${report.report_type} ${day(report.from_date)} to ${day(report.to_date)}`,
  });
}